---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.1.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.1.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.1.0
  i386: ghcr.io/hassio-addons/debian-base/i386:7.1.0
args:
  BUILD_REPO: litinoveweedle/ntopng
  BUILD_DESCRIPTION: "hassio ntop addon"
  NDPI_VERSION: "4.8-stable"
  NTOP_VERSION: "5.6-stable"
  NETFLOW2NG_VERSION: "v0.0.4"
