---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.1.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.1.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.1.0
  i386: ghcr.io/hassio-addons/debian-base/i386:7.1.0
labels:
  org.opencontainers.image.title: "Li Tin O've Weedle's Home Assistant Add-on: ntopng"
  org.opencontainers.image.description: "Community version of ntopng with opensource netflow colletor netflow2nd."
  org.opencontainers.image.source: "https://github.com/litinoveweedle/hassio-addons/ntopng"
  org.opencontainers.image.licenses: "Apache License 2.0"
